services:
  - type: web
    name: condominio-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: condominio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false

databases:
  - name: condominio-db
    databaseName: condominio
    user: condominio
