# Generated by Django 5.2.6 on 2025-09-28 19:58

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enable_btree_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonarea',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='max_days_in_advance',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='max_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='max_reservations_per_unit_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='show_who_booked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='AmenityClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='core.commonarea')),
            ],
        ),
    ]
